// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZN4ME9fWVQ1954tVPT7xPDRn_8sBuZjo',
    appId: '1:136627574889:web:6f3ffb9c62a28a89c62af8',
    messagingSenderId: '136627574889',
    projectId: 'reddit-clone-app-1e747',
    authDomain: 'reddit-clone-app-1e747.firebaseapp.com',
    storageBucket: 'reddit-clone-app-1e747.appspot.com',
    measurementId: 'G-CS6V2GQ0GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOc31RpOS3g_gLMxGKh31ODFjQmJ7TkFA',
    appId: '1:136627574889:android:f05af9c5937ce0c9c62af8',
    messagingSenderId: '136627574889',
    projectId: 'reddit-clone-app-1e747',
    storageBucket: 'reddit-clone-app-1e747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQyy-sz1jP3jrHs05bK0t6x8h3BGLca3Q',
    appId: '1:136627574889:ios:0893e9340201a68ec62af8',
    messagingSenderId: '136627574889',
    projectId: 'reddit-clone-app-1e747',
    storageBucket: 'reddit-clone-app-1e747.appspot.com',
    androidClientId: '136627574889-gj6pg0rcmtv82tn45ea7ukq260ev9o00.apps.googleusercontent.com',
    iosClientId: '136627574889-cr4e9k4igfneltmbntf6q9ikedabv8pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.newRedditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQyy-sz1jP3jrHs05bK0t6x8h3BGLca3Q',
    appId: '1:136627574889:ios:96c64563907bfdc3c62af8',
    messagingSenderId: '136627574889',
    projectId: 'reddit-clone-app-1e747',
    storageBucket: 'reddit-clone-app-1e747.appspot.com',
    androidClientId: '136627574889-gj6pg0rcmtv82tn45ea7ukq260ev9o00.apps.googleusercontent.com',
    iosClientId: '136627574889-d4c6ugtrj6nslc902ihoc4l0r8qlidve.apps.googleusercontent.com',
    iosBundleId: 'com.example.newRedditClone.RunnerTests',
  );
}
